# Generated by Django 5.1.7 on 2025-03-22 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=1000, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('cuisine', models.TextField(blank=True, null=True)),
                ('course', models.TextField(blank=True, null=True)),
                ('prep_time', models.TimeField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.BinaryField(blank=True, null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.users')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'Reviews',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.users'),
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bookmark_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookmark_date', models.DateField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='products.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='products.users')),
            ],
            options={
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'Bookmarks',
            },
        ),
    ]
