// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaQqR7d-aTGjAteu7MFV8fv9Trm6Maj78',
    appId: '1:523845575062:web:8c6f9b797bf93accf2bdb7',
    messagingSenderId: '523845575062',
    projectId: 'chateo-72766',
    authDomain: 'chateo-72766.firebaseapp.com',
    storageBucket: 'chateo-72766.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR2pCII25R74xIPp1L8yCJcS8OgODPXiM',
    appId: '1:523845575062:android:824cae4889555eaaf2bdb7',
    messagingSenderId: '523845575062',
    projectId: 'chateo-72766',
    storageBucket: 'chateo-72766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSGYcgWwrnzz1BkOBLgOvSz4-LUSUWnR4',
    appId: '1:523845575062:ios:5016155e1dc5fcaef2bdb7',
    messagingSenderId: '523845575062',
    projectId: 'chateo-72766',
    storageBucket: 'chateo-72766.appspot.com',
    iosClientId: '523845575062-gon6nhmjadqfcllgkcfv7figisg3l0aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

}