# Generated by Django 5.2 on 2025-04-05 23:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=1000, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('cuisine', models.TextField(blank=True, null=True)),
                ('course', models.TextField(blank=True, null=True)),
                ('prep_time', models.TimeField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'db_table': 'Recipes',
            },
        ),
    ]
