# Generated by Django 5.2 on 2025-04-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_cook_time_alter_recipes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='video_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
