# Generated by Django 5.2 on 2025-04-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='users',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
