# Generated by Django 5.2 on 2025-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_id_users_id_remove_users_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
